import { ServicePageData } from "@/types/services";

export const behaviorTherapyData: ServicePageData = {
  hero: {
    headline: "Behavior Therapy (ABA) for Children in Bangalore",
    subheadline: "Building critical life skills and emotional regulation through positive, child-centered behavior support.",
    trustBadge: "Certified ABA Practitioners",
    primaryCTA: {
      text: "Book Consultation",
      href: "/booking/checkout?type=consultation&service=behavior-therapy",
    },
    secondaryCTA: {
      text: "View specialists",
      href: "#specialists",
    },
  },
  signs: [
    { id: "tantrums", text: "Frequent Melt-downs", icon: "🌋" },
    { id: "rigid", text: "Difficulty with Change", icon: "🧱" },
    { id: "focus", text: "Hard to Stay on Task", icon: "🔭" },
    { id: "social-gap", text: "Social Interaction Gaps", icon: "🧩" },
  ],
  conditions: [
    {
      id: "asd",
      title: "Autism Support",
      description: "Using evidence-based ABA to build language, social, and academic skills in a playful environment.",
      icon: "🌈",
    },
    {
      id: "adhd",
      title: "ADHD Management",
      description: "Strategies to improve impulse control, focus, and organization for school and home.",
      icon: "⚡",
    },
    {
      id: "aggression",
      title: "Challenging Behaviors",
      description: "Understanding the 'why' behind behaviors to teach safer, more effective ways of communicating needs.",
      icon: "🛑",
    },
    {
      id: "regulation",
      title: "Emotional Regulation",
      description: "Helping children identify and manage big feelings before they lead to distress.",
      icon: "❤️",
    },
  ],
  ageGroups: [
    {
      id: "toddlers",
      title: "Early Learners",
      ageRange: "2 - 6 Years",
      description: "Play-based naturalistic teaching to establish core communication and social skills.",
      focusPoints: ["Requesting", "Turn taking", "Instruction following", "Potty training"],
      icon: "🍼",
    },
    {
      id: "school",
      title: "School Age",
      ageRange: "7 - 12 Years",
      description: "Community-based skills, academic support, and higher-level social communication.",
      focusPoints: ["Friendship skills", "Self-management", "Academic focus"],
      icon: "🎒",
    },
    {
      id: "pre-teen",
      title: "Pre-Teens",
      ageRange: "13+ Years",
      description: "Focusing on vocational readiness, safety skills, and independent social navigation.",
      focusPoints: ["Problem solving", "Community safety", "Executive function"],
      icon: "📱",
    },
  ],
  steps: [
    { title: "Functional Assessment", description: "Our BCBA/Specialists observe and identify the purpose of current behaviors." },
    { title: "Customized Plan", description: "A data-driven plan targeting the specific skills your child needs to thrive." },
    { title: "Active Coaching", description: "Therapists work with your child while coaching you for 24/7 success." },
  ],
  valueProps: [
    { title: "Data-Driven", description: "We track every milestone meticulously to ensure we're always trending up.", icon: "📊" },
    { title: "Positive Reinforcement", description: "No punishment. We leverage your child's natural interests to motivate learning.", icon: "🎁" },
    { title: "Life Skills First", description: "We prioritize skills that give your child the most independence immediately.", icon: "🔑" },
  ],
  faqs: [
    { question: "Is ABA therapy intensive?", answer: "Intensity varies. We recommend anywhere from 10 to 20 hours a week depending on the child's needs." },
    { question: "Do parents need to be involved?", answer: "Absolutely. Parent training is a core part of our model to ensure skills generalize." },
    { question: "What is your approach to ABA?", answer: "We use a neuro-affirmative, naturalistic approach (NDBI) that respects the child's autonomy." },
  ],
  pricing: {
    basePrice: 1500,
    currency: "INR",
    description: "Per 60-minute behavior support session",
  },
  therapists: [
    {
      id: "exp-3",
      name: "Priyanka Murthy",
      provider_type: "Behavior Specialist",
      category: "Behavior Therapy",
      avatar_url: "/images/experts/behavioral_specialist.png",
      experience_years: 9,
      rating_avg: 4.8,
      review_count: 156,
      specializations: ["Autism Communication", "Social Skills", "Positive Behavior Support"],
      first_session_price: 1300,
      is_verified: true,
      bio: "Certified therapist specializing in Naturalistic Developmental Behavioral Interventions (NDBI). Priyanka focuses on building functional communication and social joy for neurodivergent children.",
      total_bookings: 340,
    },
    {
      id: "exp-6",
      name: "David Raj",
      provider_type: "Behavior Specialist",
      category: "Behavior Therapy",
      avatar_url: "/images/experts/autism_specialist.png",
      experience_years: 8,
      rating_avg: 4.7,
      review_count: 112,
      specializations: ["Early Start Denver Model", "VB-MAPP", "Positive Behavior Support"],
      first_session_price: 1500,
      is_verified: true,
      bio: "Expert in early intensive behavioral intervention with a focus on Natural Environment Teaching (NET). David excels at integrating therapy into the child's daily play and school routines.",
      total_bookings: 210,
    },
    {
      id: "exp-16",
      name: "Siddharth Varma",
      provider_type: "Senior Behavior Analyst",
      category: "Behavior Therapy",
      avatar_url: "/images/experts/expert_1.png",
      experience_years: 11,
      rating_avg: 5.0,
      review_count: 198,
      specializations: ["Challenging Behaviors", "Parent Coaching", "Skill Acquisition"],
      first_session_price: 1800,
      is_verified: true,
      bio: "With over a decade of experience, Siddharth specializes in helping families navigate complex behavioral challenges using empathetic, data-driven strategies.",
      total_bookings: 480,
    },
  ],
  metadata: {
    title: "Behavior Therapy (ABA) for Kids in Bangalore | Autism & ADHD Support",
    description: "Expert behavior therapy and ABA support in Bangalore. Specialized care for autism, ADHD, and emotional regulation. Personalized plans for every child.",
    keywords: ["Behavior therapy Bangalore", "ABA therapy for autism", "ADHD child counselor", "Positive behavior support"],
  }
};
