import { ServicePageData } from "@/types/services";

export const childCounselingData: ServicePageData = {
  hero: {
    headline: "Psychology & Child Counseling in Bangalore",
    subheadline: "A safe space for children to express, regulate, and grow resilient through compassionate, child-led therapy.",
    trustBadge: "RCI Registered Psychologists",
    primaryCTA: {
      text: "Book a Safe Space",
      href: "/booking/checkout?type=consultation&service=child-counseling",
    },
    secondaryCTA: {
      text: "Talk to an Expert",
      href: "#specialists",
    },
  },
  signs: [
    { id: "anxiety", text: "Social Anxiety", icon: "😟" },
    { id: "anger", text: "Aggression/Anger", icon: "😡" },
    { id: "sleep", text: "Sleep Disturbances", icon: "🌙" },
    { id: "withdrawal", text: "Social Withdrawal", icon: "🚪" },
  ],
  conditions: [
    {
      id: "anxiety-disorder",
      title: "Anxiety & Fears",
      description: "Helping children manage school refusal, separation anxiety, and phobias.",
      icon: "🎈",
    },
    {
      id: "social-skills",
      title: "Social-Emotional Skills",
      description: "Building empathy, emotional intelligence, and peer interaction strategies.",
      icon: "🤝",
    },
    {
      id: "behavioral",
      title: "Behavioral Challenges",
      description: "Address oppositional behavior through CBT and play therapy approaches.",
      icon: "🧩",
    },
    {
      id: "trauma",
      title: "Grief & Trauma",
      description: "Support for children dealing with loss, relocation, or difficult life changes.",
      icon: "🕊️",
    },
  ],
  ageGroups: [
    {
      id: "play-age",
      title: "Play Therapy",
      ageRange: "3 - 8 Years",
      description: "Using toys, art, and storytelling to help young children communicate what they can't yet put into words.",
      focusPoints: ["Emotional expression", "Attachment", "Anxiety reducing"],
      icon: "🎨",
    },
    {
      id: "tween-counsel",
      title: "Tweens",
      ageRange: "9 - 13 Years",
      description: "Addressing self-esteem, peer pressure, and academic stress with active listening and CBT tools.",
      focusPoints: ["Self-image", "Resilience", "Stress management"],
      icon: "🎧",
    },
    {
      id: "adolescent-counsel",
      title: "Adolescents",
      ageRange: "14+ Years",
      description: "Supporting identity formation, career anxiety, and complex emotional regulation.",
      focusPoints: ["Identity", "Relationships", "Coping skills"],
      icon: "📱",
    },
  ],
  steps: [
    { title: "Intake Session", description: "Meeting with parents first to understand the family context and child's history." },
    { title: "Rapport Building", description: "The most critical phase where the counselor establishes trust with the child." },
    { title: "Therapeutic Journey", description: "Evidence-based interventions (CBT, Play Therapy) delivered weekly." },
  ],
  valueProps: [
    { title: "Child-Led", description: "We respect the child's pace and comfort, never forcing a narrative.", icon: "🕊️" },
    { title: "Confidential", description: "A secure environment following strictly ethical guidelines.", icon: "🔐" },
    { title: "Family Support", description: "We provide monthly parent-coaching sessions to help the whole home evolve.", icon: "👨‍👩‍👧" },
  ],
  faqs: [
    { question: "Will I know what my child talks about?", answer: "We maintain basic confidentiality for trust, but always share safety concerns and general progress with parents." },
    { question: "How many sessions are needed?", answer: "Most emotional challenges require 8-12 sessions for sustainable change." },
    { question: "Do you offer online counseling?", answer: "Yes, especially for older children (9+) who are comfortable with video calls." },
  ],
  pricing: {
    basePrice: 1500,
    currency: "INR",
    description: "Per 60-minute confidential session",
  },
  therapists: [
    {
      id: "exp-9",
      name: "Dr. Ananya Kapoor",
      tagline: "Child Psychologist",
      category: "Child Counseling",
      avatar_url: "/images/experts/counselor.png",
      experience_years: 12,
      rating: 4.9,
      review_count: 142,
      specializations: ["CBT", "Social Skills", "Play Therapy", "Adolescent Mental Health"],
      first_session_price: 1800,
      is_verified: true,
      bio: "Ph.D. in Clinical Child Psychology with 12+ years experience. Dr. Ananya specializes in Cognitive Behavioral Therapy and play-based assessments for emotional regulation and resilience.",
      booking_count: 380,
    },
    {
      id: "exp-10",
      name: "Meghna Roy",
      tagline: "Counseling Psychologist",
      category: "Child Counseling",
      avatar_url: "/images/experts/special_educator.png",
      experience_years: 7,
      rating: 4.8,
      review_count: 86,
      specializations: ["Grief Counseling", "Art Therapy", "Parental Support"],
      first_session_price: 1500,
      is_verified: true,
      bio: "A compassionate counselor using creative arts and narrative therapy to help children navigate difficult life transitions, loss, and anxiety in a safe, judgment-free space.",
      booking_count: 160,
    },
    {
      id: "exp-17",
      name: "Zoya Khan",
      tagline: "Senior Child Counselor",
      category: "Child Counseling",
      avatar_url: "/images/experts/expert_4.png",
      experience_years: 9,
      rating: 4.9,
      review_count: 124,
      specializations: ["Self-Esteem", "School Refusal", "Behavioral Coaching"],
      first_session_price: 1600,
      is_verified: true,
      bio: "Specialist in school-related mental health and social transitions. Zoya works closely with children and schools to foster an environment of emotional success.",
      booking_count: 240,
    },
  ],
  metadata: {
    title: "Child Counseling & Psychology Bangalore | Play Therapy & CBT",
    description: "Professional child counseling and pediatric psychology in Bangalore. Specializing in play therapy, CBT for kids, anxiety management, and behavioral support in a safe space.",
    keywords: ["Child psychologist Bangalore", "Kids counseling near me", "Play therapy Bangalore", "Child behavior specialist"],
  }
};
