import { ServicePageData } from "@/types/services";

export const earlyInterventionData: ServicePageData = {
  hero: {
    headline: "Early Intervention: The Foundation for Your Child's Future",
    subheadline: "Every month matters. Our expert-led early intervention programs in Bangalore help infants and toddlers bridge developmental gaps through play and parent participation.",
    trustBadge: "Specialized Early Childhood Experts",
    primaryCTA: {
      text: "Start Assessment",
      href: "/booking/checkout?type=consultation&service=early-intervention",
    },
    secondaryCTA: {
      text: "Meet our Specialists",
      href: "#specialists",
    },
  },
  signs: [
    { id: "eye-contact", text: "Limited Eye Contact", icon: "👀" },
    { id: "pointing", text: "Not Pointing to Needs", icon: "☝️" },
    { id: "joint-attention", text: "Difficulty Sharing Focus", icon: "🤝" },
    { id: "response", text: "Inconsistent Name Response", icon: "👂" },
  ],
  conditions: [
    {
      id: "delayed-milestones",
      title: "Delayed Milestones",
      description: "Supporting children who aren't hitting expected physical, social, or communication goals on time.",
      icon: "⏳",
    },
    {
      id: "sensory-processing",
      title: "Sensory Processing",
      description: "Helping infants regulate their responses to sounds, lights, textures, and movement.",
      icon: "🌈",
    },
    {
      id: "social-emotional",
      title: "Social-Emotional Skills",
      description: "Building the core capacity for connection, imitation, and emotional regulation from the start.",
      icon: "🌱",
    },
    {
      id: "motor-coordination",
      title: "Motor Coordination",
      description: "Addressing 'clumsiness' or delays in crawling, walking, and grasping objects.",
      icon: "🤸",
    },
  ],
  ageGroups: [
    {
      id: "infants",
      title: "Infants",
      ageRange: "0 - 18 Months",
      description: "Focus on sensory regulation, joint attention, and early communication foundations.",
      focusPoints: ["Imitation skills", "Social smiling", "Vocal play", "Sensory settling"],
      icon: "🍼",
    },
    {
      id: "toddlers",
      title: "Toddlers",
      ageRange: "18 - 36 Months",
      description: "Expanding communication, self-help skills, and peer-related social foundations.",
      focusPoints: ["Functional play", "Asking for needs", "Following routines", "Transitioning"],
      icon: "🐣",
    },
    {
      id: "preschool-entry",
      title: "Preschool Prep",
      ageRange: "3 Years",
      description: "Getting ready for group environments while strengthening individual core competencies.",
      focusPoints: ["Group listening", "Independent play", "Self-care", "Social interaction"],
      icon: "🏫",
    },
  ],
  steps: [
    { title: "Home-Based Screening", description: "Our specialists visit your home to observe the child in their natural, comfortable environment." },
    { title: "Multidisciplinary Plan", description: "A combined approach involving ST, OT, and Behavior experts as needed for holistic growth." },
    { title: "Parent Empowerment", description: "Weekly coaching to ensure you know how to turn everyday moments into learning opportunities." },
  ],
  valueProps: [
    { title: "Brain Plasticity Focus", description: "We leverage the 'golden window' of brain development when it's most adaptable.", icon: "🧠" },
    { title: "Natural Environment", description: "We work where the child plays, eats, and sleeps—to ensure skills actually stick.", icon: "🏠" },
    { title: "Holistic Care", description: "We don't just fix symptoms; we build the whole child's capacity for independence.", icon: "🌟" },
  ],
  faqs: [
    { question: "Is my child too young for therapy?", answer: "Never. Early intervention can start as early as 6 months. Waiting often makes challenges harder to overcome later." },
    { question: "Is this done at home?", answer: "Yes, we highly recommend home-based sessions for children under 3 to ensure they feel safe and comfortable." },
    { question: "Can I be in the session?", answer: "Yes! In fact, we require parent presence to coach you on implementing the strategies daily." },
  ],
  pricing: {
    basePrice: 1600,
    currency: "INR",
    description: "Per 60-minute specialized Early Intervention session",
  },
  therapists: [
    {
      id: "exp-7",
      name: "Meera Krishnan",
      provider_type: "Early Intervention Specialist",
      category: "Early Intervention",
      avatar_url: "/images/experts/early_intervention.png",
      experience_years: 11,
      rating_avg: 4.9,
      review_count: 184,
      specializations: ["Infant Communication", "Sensory Integration", "Parent Coaching"],
      first_session_price: 1500,
      is_verified: true,
      bio: "Meera is an expert in Naturalistic Developmental Behavioral Interventions (NDBI). She specializes in transforming everyday home routines into powerful learning opportunities for infants and toddlers.",
      total_bookings: 380,
    },
    {
      id: "exp-8",
      name: "Dr. Kavita Rao",
      provider_type: "Developmental Therapist",
      category: "Early Intervention",
      avatar_url: "/images/experts/occupational_therapist.png",
      experience_years: 14,
      rating_avg: 4.8,
      review_count: 245,
      specializations: ["Floortime Mode", "Milestone Tracking", "Joint Attention"],
      first_session_price: 1800,
      is_verified: true,
      bio: "With a background in pediatric neuro-rehabilitation, Dr. Kavita uses play-based floor-time models to address core developmental hurdles and foster deep parent-child connection.",
      total_bookings: 520,
    },
    {
      id: "exp-13",
      name: "Radhika Nair",
      provider_type: "Early Childhood Specialist",
      category: "Early Intervention",
      avatar_url: "/images/experts/expert_3.png",
      experience_years: 8,
      rating_avg: 4.9,
      review_count: 112,
      specializations: ["Play-Based Skills", "Toddler Transitions", "Social Emotional Learning"],
      first_session_price: 1400,
      is_verified: true,
      bio: "Radhika specializes in prepareing children for social environments like preschool by building foundational self-regulation and communication skills through joy-led interaction.",
      total_bookings: 210,
    },
  ],
  metadata: {
    title: "Early Intervention for Infants & Toddlers Bangalore | Milestone Support",
    description: "Specialized early intervention for infants and toddlers in Bangalore. Bridge developmental gaps through play-based therapy and expert parent coaching. Start as early as 6 months.",
    keywords: ["Early intervention Bangalore", "Developmental delay support", "Infant milestone therapy", "Play-based pediatric therapy"],
  }
};
