import { Provider } from "@/types";

export const DUMMY_EXPERTS: any[] = [
  {
    id: "exp-1",
    name: "Lakshmy Balachandran",
    provider_type: "Speech Language Pathologist",
    category: "Speech Therapy",
    avatar_url: "/images/experts/speech_therapist.png",
    experience_years: 6,
    rating_avg: 4.8,
    review_count: 121,
    specializations: ["Speech Delay", "Early Intervention", "Articulation"],
    consultation_fee: 1200,
    is_verified: true,
    city: "Bangalore",
    bio: "Certified therapist specializing in early childhood language development and neuro-affirmative communication strategies.",
    total_bookings: 120,
    mode: "Home / Clinic"
  },
  {
    id: "exp-2",
    name: "Dr. Sandeep Singh",
    provider_type: "Senior Consultant",
    category: "Speech Therapy",
    avatar_url: "/images/experts/autism_specialist.png",
    experience_years: 12,
    rating_avg: 4.9,
    review_count: 345,
    specializations: ["Stuttering Specialist", "Fluency", "Adult Speech"],
    consultation_fee: 1500,
    is_verified: true,
    city: "Delhi",
    bio: "Over a decade of experience in fluency disorders and pediatric speech assessments with a focus on confidence building.",
    total_bookings: 345,
    mode: "Online / Home"
  },
  {
    id: "exp-3",
    name: "Priyanaka Murthy",
    provider_type: "Behavior Specialist",
    category: "Behavior Therapy",
    avatar_url: "/images/experts/behavioral_specialist.png",
    experience_years: 8,
    rating_avg: 4.7,
    review_count: 89,
    specializations: ["Autism Communication", "Social Skills", "ABA"],
    consultation_fee: 1300,
    is_verified: true,
    city: "Bangalore",
    bio: "Helping children with ASD navigate social complexities and build functional communication through neuro-inclusive care.",
    total_bookings: 150,
    mode: "Clinic"
  },
  {
    id: "exp-4",
    name: "Anjali Nair",
    provider_type: "Occupational Therapist",
    category: "Occupational Therapy",
    avatar_url: "/images/experts/special_educator.png",
    experience_years: 7,
    rating_avg: 4.9,
    review_count: 156,
    specializations: ["Sensory Integration", "Fine Motor Skills"],
    consultation_fee: 1400,
    is_verified: true,
    city: "Mumbai",
    bio: "Passionate about sensory processing and helping children achieve independence in their daily living activities.",
    total_bookings: 180,
    mode: "Home / Online"
  }
];
