import { ServicePageData } from "@/types/services";

export const occupationalTherapyData: ServicePageData = {
  hero: {
    headline: "Occupational Therapy for Children in Bangalore",
    subheadline: "Empowering children to master daily activities, refine motor skills, and navigate sensory worlds with confidence and joy.",
    trustBadge: "Trusted by 500+ Families",
    primaryCTA: {
      text: "Book Assessment",
      href: "/booking/checkout?type=consultation&service=occupational-therapy",
    },
    secondaryCTA: {
      text: "View Specialists",
      href: "#specialists",
    },
  },
  signs: [
    { id: "sensory-seeking", text: "Sensory Seeking", icon: "🌀" },
    { id: "fine-motor", text: "Struggles with Writing", icon: "✏️" },
    { id: "clumsiness", text: "Frequent Falls/Clumsy", icon: "🤸" },
    { id: "dressing", text: "Difficulty Dressing", icon: "👕" },
  ],
  conditions: [
    {
      id: "spd",
      title: "Sensory Processing Disorder",
      description: "Helping children manage over or under-responsiveness to touch, sound, and movement.",
      icon: "🧠",
    },
    {
      id: "motor-delay",
      title: "Motor Skill Delay",
      description: "Developing the strength and coordination needed for handwriting, sports, and self-care.",
      icon: "🏃",
    },
    {
      id: "dyspraxia",
      title: "Dyspraxia (DCD)",
      description: "Improving planning and execution of physical movements for smoother daily life.",
      icon: "🧩",
    },
    {
      id: "adl",
      title: "Activities of Daily Living",
      description: "Training in basic life skills like eating, dressing, and hygiene for independence.",
      icon: "🏠",
    },
  ],
  ageGroups: [
    {
      id: "early-years",
      title: "Early Intervention",
      ageRange: "0 - 4 Years",
      description: "Focusing on developmental milestones, floor-time play, and sensory exploration.",
      focusPoints: ["Grasping", "Crawling/Walking", "Sensory play", "Feeding"],
      icon: "🧸",
    },
    {
      id: "primary",
      title: "School Age",
      ageRange: "5 - 12 Years",
      description: "Optimizing classroom performance, handwriting, and social participation.",
      focusPoints: ["Handwriting", "Attention span", "Bilateral coordination"],
      icon: "🖍️",
    },
    {
      id: "teens",
      title: "Adolescents",
      ageRange: "13+ Years",
      description: "Building independence, vocational skills, and complex motor coordination.",
      focusPoints: ["Life skills", "Ergonomics", "Emotional regulation"],
      icon: "🚲",
    },
  ],
  steps: [
    { title: "Sensory Mapping", description: "We start by understanding your child's unique sensory profile and motor baseline." },
    { title: "Goal Setting", description: "Defining functional goals that matter to your family's daily routine." },
    { title: "Active Therapy", description: "Engaging sessions that feel like play but build real-world neuro-connections." },
  ],
  valueProps: [
    { title: "Holistic Growth", description: "We look beyond the deficit to build the whole child's capacity for engagement.", icon: "🌟" },
    { title: "In-Home Success", description: "Therapy in the environment where the skills will actually be used.", icon: "🏘️" },
    { title: "Expert Vetting", description: "Work with only the top 5% of pediatric occupational therapists in Bangalore.", icon: "🏅" },
  ],
  faqs: [
    { question: "How is OT different from PT?", answer: "PT focuses on mobility and gross motor, while OT focuses on functional participation, fine motor, and sensory processing." },
    { question: "Is OT only for sensory issues?", answer: "No, OT covers everything from handwriting and dressing to attention and social play skills." },
    { question: "How many sessions per week?", answer: "Usually 2 sessions per week provide a good balance for consistent progress." },
  ],
  pricing: {
    basePrice: 1400,
    currency: "INR",
    description: "Per 60-minute specialized session",
  },
  therapists: [
    {
      id: "exp-4",
      name: "Anjali Nair",
      tagline: "Occupational Therapist",
      category: "Occupational Therapy",
      avatar_url: "/images/experts/occupational_therapy.png",
      experience_years: 8,
      rating: 4.9,
      review_count: 156,
      specializations: ["Sensory Integration", "Fine Motor Skills", "Handwriting"],
      first_session_price: 1400,
      is_verified: true,
      bio: "RCI registered therapist with 8+ years specializing in Sensory Integration-based approaches for SPD and coordination challenges in early learners.",
      booking_count: 320,
    },
    {
      id: "exp-5",
      name: "Dr. Vikram Raj",
      tagline: "Senior Pediatric OT",
      category: "Occupational Therapy",
      avatar_url: "/images/experts/autism_specialist.png",
      experience_years: 12,
      rating: 4.8,
      review_count: 210,
      specializations: ["NDT", "Pediatric Rehabilitation", "Postural Care"],
      first_session_price: 1600,
      is_verified: true,
      bio: "Expert in neuro-developmental techniques (NDT) with a focus on motor planning and functional independence for children with complex physical needs.",
      booking_count: 540,
    },
    {
      id: "exp-15",
      name: "Sanya Gupta",
      tagline: "Pediatric OT",
      category: "Occupational Therapy",
      avatar_url: "/images/experts/expert_5.png",
      experience_years: 6,
      rating: 4.7,
      review_count: 98,
      specializations: ["ADL Training", "School Readiness", "Executive Function"],
      first_session_price: 1300,
      is_verified: true,
      bio: "Dedicated to building the physical and cognitive foundations for school success through play-based activities that enhance daily living skills.",
      booking_count: 180,
    },
  ],
  metadata: {
    title: "Occupational Therapy for Kids in Bangalore | Sensory & Motor Skills",
    description: "Pediatric occupational therapy in Bangalore. Specializing in sensory processing, motor skills development, and functional independence for children and teens.",
    keywords: ["Occupational therapy Bangalore", "Pediatric OT", "Sensory integration therapy", "Fine motor skills training"],
  }
};
