import { ServicePageData } from "@/types/services";

export const physiotherapyData: ServicePageData = {
  hero: {
    headline: "Pediatric Physiotherapy in Bangalore",
    subheadline: "Optimizing physical potential and mobility to help your child explore the world without limits.",
    trustBadge: "Expert Neuro-Physiotherapists",
    primaryCTA: {
      text: "Book Mobility Audit",
      href: "/booking/checkout?type=consultation&service=physiotherapy",
    },
    secondaryCTA: {
      text: "Meet our Specialists",
      href: "#specialists",
    },
  },
  signs: [
    { id: "walking", text: "Toe Walking", icon: "👣" },
    { id: "posture", text: "Poor Posture/Slouching", icon: "🧍" },
    { id: "stiffness", text: "Muscle Stiffness", icon: "🦾" },
    { id: "balance", text: "Poor Balance", icon: "⚖️" },
  ],
  conditions: [
    {
      id: "cp",
      title: "Cerebral Palsy",
      description: "Comprehensive management focused on improving gait, tone, and functional mobility.",
      icon: "♿",
    },
    {
      id: "gross-motor",
      title: "Gross Motor Delay",
      description: "Helping children hit physical milestones like rolling, sitting, and independent walking.",
      icon: "🏃",
    },
    {
      id: "postural",
      title: "Postural Correction",
      description: "Correcting scoliosis, flat feet, and other structural alignments through targeted exercise.",
      icon: "📐",
    },
    {
      id: "neuro-rehab",
      title: "Neurological Rehab",
      description: "Intensive therapy for pediatric neurological conditions and post-surgery recovery.",
      icon: "🧠",
    },
  ],
  ageGroups: [
    {
      id: "infant-pt",
      title: "Infant Care",
      ageRange: "0 - 2 Years",
      description: "Focusing on head control, trunk stability, and early movement exploration.",
      focusPoints: ["Neck control", "Tummy time success", "Rolling", "Early crawling"],
      icon: "👶",
    },
    {
      id: "toddler-pt",
      title: "Active Toddlers",
      ageRange: "3 - 7 Years",
      description: "Refining gait patterns, balance, and the strength needed for playground participation.",
      focusPoints: ["Running", "Jumping", "Climbing", "Coordination games"],
      icon: "🎠",
    },
    {
      id: "sports-pt",
      title: "Sports & Posture",
      ageRange: "8+ Years",
      description: "Injury prevention, postural health, and physical stamina for school-age children.",
      focusPoints: ["Core strength", "Ergonomics", "Flexibility", "Sports skills"],
      icon: "⚽",
    },
  ],
  steps: [
    { title: "Physical Assessment", description: "Measuring range of motion, muscle tone, and developmental current level." },
    { title: "Rehab Roadmap", description: "Setting specific physical targets like 'independent sitting' or 'stairs navigation'." },
    { title: "Manual & Exercise", description: "A combination of manual techniques and fun, active exercises." },
  ],
  valueProps: [
    { title: "Expert Mobility", description: "Our specialists are trained in the latest neuro-physio protocols.", icon: "🏅" },
    { title: "Home Convenience", description: "Intensive physical therapy is more effective in a familiar, relaxed home setting.", icon: "🏠" },
    { title: "Equipment Advice", description: "We help you choose and adapt assistive devices for your child's home.", icon: "🦽" },
  ],
  faqs: [
    { question: "Is pediatric PT only for serious conditions?", answer: "No, many children visit us for orthopaedic issues, toe walking, or general clumsiness." },
    { question: "How long are the sessions?", answer: "Usually 45 to 60 minutes depending on the child's stamina." },
    { question: "Can PT and OT happen together?", answer: "Absolutely. We often coordinate with Occupational Therapists for a combined care approach." },
  ],
  pricing: {
    basePrice: 1200,
    currency: "INR",
    description: "Per 60-minute intensive physio session",
  },
  therapists: [
    {
      id: "exp-11",
      name: "Dr. Kavita Nair",
      tagline: "Pediatric Physiotherapist",
      category: "Physiotherapy",
      avatar_url: "/images/experts/physiotherapist.png",
      experience_years: 15,
      rating: 4.9,
      review_count: 242,
      specializations: ["Neuro-Rehab", "Cerebral Palsy", "Gait Correction"],
      first_session_price: 1500,
      is_verified: true,
      bio: "Master of pediatric physical rehabilitation with 15+ years experience. Dr. Kavita specializes in neuro-developmental therapy and gait correction for children with neuromuscular challenges.",
      booking_count: 620,
    },
    {
      id: "exp-12",
      name: "Arjun Khanna",
      tagline: "Physical Therapist",
      category: "Physiotherapy",
      avatar_url: "/images/experts/speech_therapist.png",
      experience_years: 6,
      rating: 4.7,
      review_count: 58,
      specializations: ["Posture Correction", "Sports Injuries", "Balance Training"],
      first_session_price: 1200,
      is_verified: true,
      bio: "An energetic therapist focused on making exercise fun and engaging. Arjun specializes in posture correction for school-aged children and recovery from sports-related injuries.",
      booking_count: 140,
    },
    {
      id: "exp-18",
      name: "Deepa Menon",
      tagline: "Senior Physiotherapist",
      category: "Physiotherapy",
      avatar_url: "/images/experts/expert_2.png",
      experience_years: 10,
      rating: 4.8,
      review_count: 156,
      specializations: ["Gross Motor Delay", "Aquatic Therapy", "Strengthening"],
      first_session_price: 1300,
      is_verified: true,
      bio: "Deepa focuses on helping children meet their physical milestones through evidence-based strengthening exercises and creative mobility training.",
      booking_count: 310,
    },
  ],
  metadata: {
    title: "Pediatric Physiotherapy Bangalore | Kids Mobility & Neuro Rehab",
    description: "Expert pediatric physiotherapy in Bangalore. Specialized care for cerebral palsy, gross motor delays, postural correction, and neuro-rehabilitation for children.",
    keywords: ["Pediatric physiotherapy Bangalore", "Child physio near me", "Neuro rehab for kids", "Gross motor skills therapy"],
  }
};
