import { ServicePageData } from "@/types/services";

export const speechTherapyData: ServicePageData = {
  hero: {
    headline: "Speech Therapy for Children in Bangalore",
    subheadline: "Helping late talkers, stuttering, and communication challenges — with neuro-affirmative care that celebrates your child's voice.",
    trustBadge: "500+ Happy Families in Bangalore",
    primaryCTA: {
      text: "Book Assessment",
      href: "/booking/checkout?type=consultation&service=speech-therapy",
    },
    secondaryCTA: {
      text: "Meet the Specialists",
      href: "/booking/checkout?type=consultation&service=speech-therapy",
    },
  },
  signs: [
    { id: "delay", text: "Speech Delay", icon: "🗣️" },
    { id: "stuttering", text: "Stuttering/Fluency", icon: "➰" },
    { id: "social", text: "Social Communication", icon: "🤝" },
    { id: "clarity", text: "Clarity/Articulation", icon: "✨" },
  ],
  conditions: [
    {
      id: "delay",
      title: "Speech & Language Delay",
      description: "When a child isn't hitting verbal milestones at the expected age, we help bridge the gap efficiently.",
      icon: "📣",
    },
    {
      id: "stammering",
      title: "Stammering / Stuttering",
      description: "Building fluency and confidence through gentle, evidence-based communication strategies.",
      icon: "💬",
    },
    {
      id: "asd-comm",
      title: "Autism-Related Communication",
      description: "Supporting neurodivergent children in expressing their needs and navigating social interactions.",
      icon: "🧩",
    },
    {
      id: "social-comm",
      title: "Social Communication",
      description: "Helping children understand social nuances, body language, and the 'whys' of conversation.",
      icon: "🎭",
    },
  ],
  ageGroups: [
    {
      id: "early-intervention",
      title: "Early Steps",
      ageRange: "18 Months - 4 Years",
      description: "Critical window for brain development. We focus on play-based communication and parent training.",
      focusPoints: ["Late talking", "Joint attention", "First words", "Responsive feeding"],
      icon: "🍼",
    },
    {
      id: "preschool",
      title: "Academic Growth",
      ageRange: "5 - 12 Years",
      description: "Focusing on complex sentences, social interactions, and classroom communication.",
      focusPoints: ["Pronunciation", "Multi-step instructions", "Sentence building"],
      icon: "🎒",
    },
    {
      id: "school-age",
      title: "Social Confidence",
      ageRange: "13+ Years",
      description: "Empowering adolescents with advanced communication strategies and self-advocacy.",
      focusPoints: ["Public speaking", "Executive function", "Self-advocacy"],
      icon: "📱",
    },
  ],
  steps: [
    { title: "Clinical Evaluation", description: "A thorough 45-minute evaluation of your child's current communication profile." },
    { title: "Custom Roadmap", description: "Development of a personalized strategy with measurable functional goals." },
    { title: "Active Therapy", description: "Engaging, results-oriented therapy delivered at home or online with continuous feedback." },
  ],
  valueProps: [
    { title: "Neuro-Affirmative", description: "We value difference and focus on functional communication, not 'fixing' the child.", icon: "🌈" },
    { title: "In-Home Comfort", description: "Therapy in the natural environment leads to faster and more sustainable progress.", icon: "🏠" },
    { title: "Expert Vetting", description: "Every therapist undergoes a rigorous 5-step background and clinical verification.", icon: "🏅" },
  ],
  faqs: [
    { question: "When should we start therapy?", answer: "Early intervention is key. If you notice your child isn't reaching milestones by 18-24 months, an assessment is highly recommended." },
    { question: "Do you offer online sessions?", answer: "Yes, we offer high-quality online tele-therapy sessions that are interactive and research-backed." },
    { question: "How long is a session?", answer: "Standard sessions are 45 minutes of direct therapy, followed by a 15-minute briefing for parents." },
  ],
  pricing: {
    basePrice: 1200,
    currency: "INR",
    description: "Per 60-minute specialized session",
  },
  therapists: [
    {
      id: "exp-1",
      name: "Lakshmy Balachandran",
      provider_type: "Lead Speech Therapist",
      category: "Speech Therapy",
      avatar_url: "/images/experts/expert_1.png",
      experience_years: 12,
      rating_avg: 5.0,
      review_count: 240,
      specializations: ["Early Intervention", "Autism Spectrum", "AVT"],
      first_session_price: 1500,
      is_verified: true,
      bio: "RCI silver medalist with over a decade in pediatric speech-language pathology. Specialist in social communication and early language development.",
      total_bookings: 750,
    },
    {
      id: "exp-14",
      name: "Rohan Das",
      provider_type: "Speech Language Pathologist",
      category: "Speech Therapy",
      avatar_url: "/images/experts/expert_4.png",
      experience_years: 6,
      rating_avg: 4.8,
      review_count: 112,
      specializations: ["Fluency", "Articulation", "Voice"],
      first_session_price: 1200,
      is_verified: true,
      bio: "Expert in stuttering management and articulation therapy for school-aged children. Rohan uses a child-led approach to build confidence.",
      total_bookings: 320,
    },
    {
      id: "exp-18",
      name: "Meghna Roy",
      provider_type: "Senior Speech Therapist",
      category: "Speech Therapy",
      avatar_url: "/images/experts/expert_2.png",
      experience_years: 8,
      rating_avg: 4.9,
      review_count: 185,
      specializations: ["Oral Motor", "Feeding Therapy", "Late Talkers"],
      first_session_price: 1400,
      is_verified: true,
      bio: "Specializes in feeding challenges and early expressive language. Meghna brings a holistic family-centered approach to every session.",
      total_bookings: 440,
    },
  ],
  metadata: {
    title: "Speech Therapy for Children in Bangalore | Verified Specialists | Insighte",
    description: "Find expert speech therapists in Bangalore for speech delay, stuttering, and communication challenges. Neuro-affirmative care at home, online, or in centers.",
    keywords: ["Speech Therapy Bangalore", "Speech Therapist near me", "Child speech delay", "Stuttering therapy Bangalore", "Neuro-affirmative speech therapy"],
  },
};
